### ISSUE TITLE
Input date of birth improvement

### ISSUE THREAD

**Issue by triandamai** [TimKelompok5/mobile-app#66]

**Comment by triandamai** [comment]
![IMG-20221128-WA0007](https://user-images.githubusercontent.com/41132846/204207316-e2502ca0-6330-44dd-92fd-94dafd82c013.jpg)

**Comment by WhyUReRenldI** [comment]
![image](https://user-images.githubusercontent.com/118540362/204585283-4be45ffa-321c-4240-bc00-5da2082e6536.png)
